### ISSUE TITLE
"cliKitStore.initializeCliKitStore is not a function" error

### ISSUE THREAD

**Issue by yngwz** [carstenlebek/shopify-node-app-starter#11]
Received this error after running pnpm install and npm run on a new clone of the project. Using version 3.0.25 of @shopify/cli-kit.

```
TypeError: cliKitStore.initializeCliKitStore is not a function
    at setEnvironmentAndReturnHost (file:///Users/user/app/next.config.mjs:37:21)
    at config (file:///Users/user/app/next.config.mjs:66:18)
    at Object.normalizeConfig (/Users/user/app/node_modules/.pnpm/next@12.2.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/server/config-shared.ts:556:14)
    at Object.loadConfig [as default] (/Users/user/app/node_modules/.pnpm/next@12.2.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/server/config.ts:799:6)
    at NextServer.prepare (/Users/user/app/node_modules/.pnpm/next@12.2.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/server/next.ts:110:20)
    at /Users/user/app/node_modules/.pnpm/next@12.2.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/cli/next-dev.ts:107:
```

Console log of `cliKitStore`:
```javascript
cliKitStore [Object: null prototype] {
  createConf: [Function: createConf],
  remove: [Function: remove$2],
  getAppInfo: [Function: getAppInfo],
  setAppInfo: [Function: setAppInfo],
  clearAppInfo: [Function: clearAppInfo],
  getTheme: [Function: getTheme],
  setTheme: [Function: setTheme],
  getSession: [Function: getSession],
  setSession: [Function: setSession],
  removeSession: [Function: removeSession]
}
```

**Comment by CoolTechYT** [comment]
Same

**Comment by reikje** [comment]
PR: https://github.com/carstenlebek/shopify-node-app-starter/pull/14
